// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnNu3QfMpt_5rllrlclyaA0fcjduRIa6U',
    appId: '1:1049187549557:web:c1168447dc8c076551533c',
    messagingSenderId: '1049187549557',
    projectId: 'hirecuelocal',
    authDomain: 'hirecuelocal.firebaseapp.com',
    storageBucket: 'hirecuelocal.appspot.com',
    measurementId: 'G-7CSW4RLVXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFodgVyklcDfCq_8u6Fj13TAobqcICOkY',
    appId: '1:1049187549557:android:54122cf3f699520951533c',
    messagingSenderId: '1049187549557',
    projectId: 'hirecuelocal',
    storageBucket: 'hirecuelocal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYNyXROpuQfr3AcCYrNSL5ahheoKkXO_4',
    appId: '1:1049187549557:ios:a52178d7a6b4e99451533c',
    messagingSenderId: '1049187549557',
    projectId: 'hirecuelocal',
    storageBucket: 'hirecuelocal.appspot.com',
    iosBundleId: 'com.example.hirecueApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYNyXROpuQfr3AcCYrNSL5ahheoKkXO_4',
    appId: '1:1049187549557:ios:a52178d7a6b4e99451533c',
    messagingSenderId: '1049187549557',
    projectId: 'hirecuelocal',
    storageBucket: 'hirecuelocal.appspot.com',
    iosBundleId: 'com.example.hirecueApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnNu3QfMpt_5rllrlclyaA0fcjduRIa6U',
    appId: '1:1049187549557:web:98619dbd7c5837de51533c',
    messagingSenderId: '1049187549557',
    projectId: 'hirecuelocal',
    authDomain: 'hirecuelocal.firebaseapp.com',
    storageBucket: 'hirecuelocal.appspot.com',
    measurementId: 'G-38Z7HQN1TK',
  );
}
